# Generated by Django 4.2.3 on 2023-07-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
